apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: mysql-persistent
    app.kubernetes.io/component: mysql-persistent
    app.kubernetes.io/instance: mysql-persistent
    template: mysql-persistent-template
  name: mysql
  namespace: wordpress
spec:
  replicas: 1
