apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: wordpress-deploy- 
spec:
  pipelineRef:
    name: deploy-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: multisite
  params:
    - name: pathToYamlFile
      value: "wordpress/overlays/site2"
  serviceAccountName: pipeline
