apiVersion: v1
data:
  database-name: c2FtcGxlZGI=
  database-password: aE9uU1Joc3VKTVRDbVJpYQ==
  database-root-password: dHRnczJhYVVLbFZCVUp0eQ==
  database-user: dXNlcjdFVA==
kind: Secret
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  creationTimestamp: null
  labels:
    app: mysql-persistent
    app.kubernetes.io/component: mysql-persistent
    app.kubernetes.io/instance: mysql-persistent
    template: mysql-persistent-template
  name: mysql
  namespace: wordpress
  selfLink: /api/v1/namespaces/wordpress/secrets/mysql
type: Opaque
