apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: wordpress
  name: wordpress
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      containers:
      - image: quay.io/rcook/wordpress:1.0
        imagePullPolicy: Always
        name: wordpress
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        volumeMounts:
          - mountPath: "/opt/app-root/src"
            name: wp-config.php
            readOnly: false
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: wp-config
        secret:
          secretName: wp-config
