apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wordpress
  namespace: wordpress
spec:
  host: wordpress.demo-sysdeseng.com 
  port:
    targetPort: 8080
  to:
    kind: Service
    name: wordpress
    weight: 100
status:
  ingress:
  - conditions:
    - status: "True"
      type: Admitted

