apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: rbd-resync-images
spec:
  params:
    - name: p
      type: string 
      default: "scottpool2"
    - name: i1
      type: string
      default: "scottpool2/mysql-pv-claim-wordpress-tekton4ee0425a-8a49-11ea-a7c4-0a580a800211"
    - name: i2
      type: string
      default: "scottpool2/wp-pv-claim-wordpress-tekton4ec66036-8a49-11ea-a7c4-0a580a800211"
  tasks:
    - name: command-resync-images
      retries: 1
      taskRef:
        name: create-configmap-command
      params:
        - name: pool
          value: "$(params.p)"
        - name: action
          value: "resync"
        - name: image1
          value: "$(params.i1)"
        - name: image2
          value: "$(params.i2)"

    - name: execute-resync-command
      retries: 3
      taskRef:
        name: execute-rbd-configmap-command
      runAfter:
        - command-resync-images

    - name: delete-resync-configmap
      taskRef:
        name: delete-configmap
      runAfter:
        - execute-resync-command
